#############################
#
# 配置数据源信息
#
#############################
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url:
    username:
    password:
    hikari:
      connection-timeout: 30000             # 等待连接池分配连接的最大时长，毫秒。
      minimum-idle: 5                       # 最小连接数
      maximum-pool-size: 20                 # 最大连接数
      auto-commit: true                     # 自动提交